# -*- coding: utf-8 -*-
"""Lab 6 - 2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m1CzMqVp0F3y_DZZzWsfI57egnhYQTEE

## Exercise 1

We have to accept or reject a large shipment of items.  
For quality control purposes, we collect a sample of **200 items** and find **24 defective items** in it.

**(a)** Construct a **96% confidence interval** for the proportion of defective items in the whole shipment.  
Use the usual normal approximation formula:

$$
\hat{p} \pm z_{1-\alpha/2}\sqrt{\frac{\hat{p}(1-\hat{p})}{n}}.
$$

**(b)** The manufacturer claims that at most one in 10 items in the shipment is defective.  
At the **4%** level of significance, do we have sufficient evidence to disprove this claim?  
Do we have it at the **15%** level?

We test the hypotheses:

$$
H_0: p \le 0.10,
\qquad
H_1: p > 0.10.
$$

The test statistic is:

$$
z = \frac{\hat{p} - p_0}{\sqrt{p_0(1 - p_0)/n}}.
$$

Implement in Python.

## Exercise 2

Refer to Exercise 1
Having looked at the collected sample, we consider an alternative supplier.  
A sample of **150 items** produced by the new supplier contains **13 defective items**.

Is there significant evidence that the quality of items produced by the new supplier is higher than the quality of items in Exercise 9.10?

We test:

$$
H_0: p_2 = p_1,
\qquad
H_1: p_2 < p_1.
$$

We use the pooled test statistic for comparing two proportions:

$$
\hat{p} = \frac{x_1 + x_2}{n_1 + n_2},
$$

$$
z =
\frac{\hat{p}_2 - \hat{p}_1}
{\sqrt{\hat{p}(1 - \hat{p})\left(\frac{1}{n_1} + \frac{1}{n_2}\right)}}.
$$

What is the **P-value** of the test?

Implement in Python.

## Exercise 3

An electronic parts factory produces resistors. Statistical analysis of the output suggests that resistances follow an approximately Normal distribution with a standard deviation of **0.2 ohms**. A sample of **52 resistors** has the average resistance of **0.62 ohms**.

**(a)** Based on these data, construct a **95% confidence interval** for the population mean resistance.  
Use the known-population-standard-deviation formula (normal z-interval):

$$
\bar{X} \pm z_{1-\alpha/2}\,\frac{\sigma}{\sqrt{n}},
$$

with $\sigma=0.2$, $n=52$, $\bar{X}=0.62$, and $\alpha=0.05$.

**(b)** If the actual population mean resistance is exactly $0.6$ ohms, what is the probability that a sample mean of size $n=52$ is **0.62 or higher**?  
Compute

$$
P\!\left(\bar{X} \ge 0.62 \mid \mu=0.60\right)
= 1 - \Phi\!\left(\frac{0.62 - 0.60}{\sigma/\sqrt{n}}\right),
$$

where $\Phi$ is the standard normal CDF.

## Exercise 4

A news agency publishes results of a recent poll.  
It reports that a certain candidate has a **10-point stronger support** in town A than in town B because **45%** of the poll participants in town A and **35%** of the poll participants in town B supported the candidate.

What **margin of error** should the news agency report for each of the listed estimates: **45%**, **35%**, and **10%**?  

Notice:

- **Sample size:** 900 randomly selected registered voters in each town  
- Reported margins of error correspond to **95% confidence intervals**  
- Use the standard formula for the margin of error of a proportion:

$$
ME = z_{1-\alpha/2} \sqrt{\frac{\hat{p}(1-\hat{p})}{n}}
$$

- For the difference of proportions \(p_A - p_B\), use

$$
ME_{diff} = z_{1-\alpha/2} \sqrt{\frac{\hat{p}_A(1-\hat{p}_A)}{n_A} + \frac{\hat{p}_B(1-\hat{p}_B)}{n_B}}
$$

## Exercise 5

A factory produces electronic sensors whose output voltages are approximately Normal with **unknown mean μ** and **known standard deviation σ = 0.5 V**.  
The factory claims the sensors are centered at 5 V.  

You sample **n = 40 sensors** from the factory and find an average voltage of **5.2 V**.  

A second batch from a new supplier has **n = 35 sensors** with an average voltage of **4.95 V**.  

Additionally, a quality check counts **defective sensors** in both batches (defined as voltage < 4.5 V):

- Original batch: 3 defective  
- New batch: 1 defective

---

### Tasks

**(a)** Construct a **95% confidence interval** for the mean voltage of the original batch.

**(b)** Test at the **1% significance level** whether the original batch mean differs from 5 V.

**(c)** Test whether the new supplier’s batch has a **higher mean voltage** than the original batch at the **5% significance level**. Compute the **z statistic** and **P-value**.

**(d)** Compute the **proportion of defective sensors** in each batch and the **95% confidence interval** for each proportion.

**(e)** Test whether the new supplier has a **significantly lower defect rate** than the original batch using a **two-sample proportion z-test**.

**(f)** Simulate **10,000 samples** of size 40 from N(μ=5, σ=0.5) and compute the fraction of times the sample mean exceeds **5.2 V**. Compare this simulated probability with the analytical result from part (b).
"""